#!/bin/bash

TEMP_PASS=""

function passwordGenerator()
{
    # Génération d'un mot de passe temporaire sécurisé
    TEMP_PASS=$(sudo dmidecode -s system-serial-number)
    echo "$TEMP_PASS"
}

passwordGenerator

# Génération d'un mot de passe temporaire sécurisé

# Modification du mot de passe
if echo "goupil:$TEMP_PASS" | chpasswd; then
    echo "✅ Mot de passe temporaire défini"
else
    echo "❌ Échec du changement de mot de passe" >&2
    exit 1
fi

sudo systemctl stop timeout.service
sudo systemctl disable timeout.service
sudo systemctl stop gdm

exit 0
