#!/bin/bash

## Simple script checking for date
## this script is executed by service Timeout.service

sleep 300

FINAL_DATE=$(sudo cat /etc/profile.d/expire.sh | cut -d '=' -f2)
while true; do
    # Get the current date
    CURRENT_DATE=$(date +%s)

    # Check if the current date is the 1st of the month
    if (( $FINAL_DATE - $CURRENT_DATE < 604800 && $FINAL_DATE > $CURRENT_DATE )); then
        # Message user that he needs to pay or service will stop soon.
        zenity --notification --text="⚠️ La location de votre appareil arrivera bientôt à son terme. En l'absence de réglement de votre cotisation annuelle, votre compte sera désactivé. Veuillez prendre contact avec goupil afin d'éviter tout désagrément." --timeout=10
    fi
    if [[ $CURRENT_DATE -gt $FINAL_DATE ]]; then
        # If it is, run the script
        /opt/bin/limitator/bloque_utilisateur
    fi

    # Sleep for 24 hours before checking again
    sleep 86400
done
