#!/bin/bash

## Simple script checking for date
## this script is executed by service Timeout.service
FINAL_DATE=$(printenv END_OF_SERVICE)
while true; do
    # Get the current date
    CURRENT_DATE=$(date +%s)

    # Check if the current date is the 1st of the month
    if [[ $CURRENT_DATE -gt $FINAL_DATE ]]; then
        # If it is, run the script
        /usr/bin/bloque_utilisateur
    fi

    # Sleep for 24 hours before checking again
    sleep 86400
done
