#!/bin/bash

FINAL_DATE=$(printenv END_OF_SERVICE)
while true; do
    # Get the current date
    CURRENT_DATE=$(date +%s)

    # Check if the current date is the 1st of the month
    if [[ $CURRENT_DATE -gt $FINAL_DATE ]]; then
        # If it is, run the script
        /usr/bin/bloque_utilisateur
	echo "greater"
    fi

    # Sleep for 24 hours before checking again
    sleep 10
done
